# Generated by Django 5.1.2 on 2024-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditems',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
