# Generated by Django 5.1.2 on 2024-11-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image'),
        ('store', '0005_solditems_shipped'),
    ]

    operations = [
    ]
